### ISSUE TITLE
Can you help me build this kernel for Kali NetHunter support?

### ISSUE THREAD

**Issue by fatkhur1960** [Exynos7580/android_kernel_samsung_a3xeltexx#1]
I had problem to building galaxy a310 kernel for NetHunter

**Comment by ghost** [comment]
I don't know necessary changes so no

**Comment by fatkhur1960** [comment]
i know, but when i'm flashing the kernel, its given bootloop...
just simple necessary changes, just give atheros usb and modules support. but I do not know which one is the problem that give bootloop
